name: Publish Project
on:
  workflow_dispatch: {}
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    name: Building ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}
          path: builds/**/Argus-Win-*.msi
          if-no-files-found: error
          retention-days: 1
  release:
    needs: build
    name: Publishing Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: artifacts
      - name: Create release
        run: gh release create ${{ github.ref_name }} --generate-notes --verify-tag artifacts/**/*
        env:
          GH_TOKEN: ${{ github.token }}
